### PR TITLE
issue-208 Hero href changed

### LINKED ISSUE #208: Back link has incorrect navigation
image
navigate incorrectly to https://main--zeiss--hlxsites.hlx.page/en/semiconductor-manufacturing-technology/news-and-events/

It should instead navigate to https://www.zeiss.com/semiconductor-manufacturing-technology/news-and-events.html

Similar issue for German version of the articles as well.

### PR DESCRIPTION
**Pull request by jindaliiita**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #208 

Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/anniversary-50-years-smt
- After: https://issue-208--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/anniversary-50-years-smt

### CODE REVIEW

**Review by alinarublea — APPROVED** [review]

**Review by bosschaert — APPROVED** [review]

File: blocks/hero/hero.js [hunk 1]
```diff
@@ -19,9 +19,9 @@ export function addBackLink(block, locale, placeholders, curPath) {
   // The 2 elements are created in the 'backward' order to allow the hover over the link
   // to change the color of the arrow. They are put in the correct position via the
   // 'order' attribute in the CSS.
-  bl.innerHTML = `<a href="/${locale}/${placeholders.newseventsbase}/"
+  bl.innerHTML = `<a href=${placeholders.herohref}
```
Comment (sdmcraft) [inline blocks/hero/hero.js:22]: Looks good. Only thing I'd want to change is rename `herohref` to something like `news-and-events-url` as likely this can be used at other places as well beyond just the `hero` block.

**Review by sdmcraft — APPROVED** [review]
