### PR TITLE
Issue-169 Footer changes wrt to small screen

### LINKED ISSUE #169: Footer layout is broken on small screen
Footer layout is broken on small screen. Drop down is not coming for social media, uber zeiss, language selection etc.

**Actual Site**

actual_site2

actual_site1

---------------------------------------------------------------
**Franklin Site**
franklin_site1

franklin_site2

### PR DESCRIPTION
**Pull request by jindaliiita**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #169 

Test URLs:
- Before: https://main--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020
- After: https://issue-169--zeiss--hlxsites.hlx.live/en/semiconductor-manufacturing-technology/news-and-events/smt-press-releases/intels-preferred-quality-supplier-award-2020

### CODE REVIEW

File: blocks/footer/footer.js [hunk 1]
```diff
@@ -7,6 +7,36 @@ function addFooterInteractions(block) {
...
+      const accordionIconSymbol = accordionButton ? accordionButton.querySelector('.icon--symbol') : null;
+      const accordionButtonSibling = accordionButton ? accordionButton.nextElementSibling : null;
+
+      if (accordionButton && accordionButtonSibling) {
+        accordionButtonSibling.classList.toggle('display-hide');
+
+        accordionButton.onclick = () => {
+          const countryAccordionButtons = document.querySelectorAll('.footer-country-switch .accordion__button');
+
+          countryAccordionButtons.forEach((x) => {
```
Comment (sdmcraft) [inline blocks/footer/footer.js:24]: Probably we should add Null safety check for `countryAccordionButtons`
Similarly for `countryButtonSibling`

**Review by sdmcraft — APPROVED** [review]
